Error: Allow for custom error messages
There's two ways in which Errors get generated:
1. The player entered a bad command. This is the most likely
   way they get generated (from a user perspective)
2. The code encountered something that it couldn't handle inside
   a valid command. Syntax parsing errors, effectively. In that case
   the command is good but the input is not, so we need to send back
   an Error without terminating the whole potential sequence of commands.

For the latter case, we now allow creating an ErrorAction with just a message
to send.